spring.application.name=memberiq
server.servlet.context-path=/memberiq

##  DB Details
spring.datasource.url=jdbc:postgresql://localhost:5432/member-iq
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

template.web-app-url=http://localhost:8080/memberiq
security.permit.post-urls=/memberiq/forgot,/memberiq/reset
security.permit.logout-url=http://localhost:8080/memberiq/logout
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/memberiq
#Endpoint Scopes
app.endpoint.scopes.[/api/admin/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/profiles/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/organizations/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/membership-types/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/payment-details/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/payment-modes/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/front-offices/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/expense-categories/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/expenses/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/memberships/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/reports/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/dashobard/**]=create:admin,update:admin,delete:admin,read:admin
