spring.application.name=memberiq
server.servlet.context-path=${SERVER_CONTEXT_PATH:/memberiq}
server.port=${PORT:8080}

##  DB Details
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:member-iq}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

template.web-app-url=http://${WEB_APP_HOST:localhost}:${PORT:8080}${SERVER_CONTEXT_PATH:/memberiq}
security.permit.post-urls=/memberiq/forgot,/memberiq/reset
security.permit.logout-url=http://${WEB_APP_HOST:localhost}:${PORT:8080}${SERVER_CONTEXT_PATH:/memberiq}/logout
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${WEB_APP_HOST:localhost}:${PORT:8080}${SERVER_CONTEXT_PATH:/memberiq}/auth/realms/memberiq

# Endpoint Scopes
app.endpoint.scopes.[/api/admin/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/profiles/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/organizations/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/membership-types/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/payment-details/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/payment-modes/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/front-offices/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/expense-categories/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/expenses/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/memberships/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/reports/**]=create:admin,update:admin,delete:admin,read:admin
app.endpoint.scopes.[/api/dashobard/**]=create:admin,update:admin,delete:admin,read:admin
